export const ROUTES = {
	HOME: "/",
	LOGIN: "/login",
	REGISTER: "/register",
	FAVORITE: "/favorite",
	PRODUCT_DETAILS: "/product/:id",
	CART: "/cart",
	SHOP: "/shop",
	USER_DASHBOARD: "/user/dashboard",
	PROFILE: "/profile",
	SHIPPING: "/shipping",
	PLACE_ORDER: "/placeorder",
	ORDER: "/order/:id",
	ADMIN: "/admin",
	ADMIN_USER_LIST: "/admin/userlist",
	ADMIN_CATEGORY_LIST: "/admin/categorylist",
	ADMIN_PRODUCT_LIST: "/admin/productlist",
	ADMIN_ALL_PRODUCTS_LIST: "/admin/allproductslist",
	ADMIN_PRODUCT_LIST_PAGED: "/admin/productlist/:pageNumber",
	ADMIN_PRODUCT_UPDATE: "/admin/product/update/:_id",
	ADMIN_ORDER_LIST: "/admin/orderlist",
	ADMIN_DASHBOARD: "/admin/dashboard",
};
